<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>Syntax Highlighting Scopes Showroom</string>
    <key>fileTypes</key>
    <array>
      <string>shss</string>
    </array>
    <key>scopeName</key>
    <string>source.shss</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>match</key>
        <string>keyword.control.php</string>
        <key>name</key>
        <string>keyword.control.php</string>
      </dict>
      <dict>
        <key>match</key>
        <string>keyword.control.ruby</string>
        <key>name</key>
        <string>keyword.control.ruby</string>
      </dict>
      <dict>
        <key>match</key>
        <string>keyword.control.python</string>
        <key>name</key>
        <string>keyword.control.python</string>
      </dict>
      <dict>
        <key>match</key>
        <string>comment.line</string>
        <key>name</key>
        <string>comment.line</string>
      </dict>
      <dict>
        <key>match</key>
        <string>comment.block</string>
        <key>name</key>
        <string>comment.block</string>
      </dict>
      <dict>
        <key>match</key>
        <string>comment.block.documentation</string>
        <key>name</key>
        <string>comment.block.documentation</string>
      </dict>
      <dict>
        <key>match</key>
        <string>punctuation.definition.comment</string>
        <key>name</key>
        <string>punctuation.definition.comment</string>
      </dict>
      <dict>
        <key>match</key>
        <string>meta.toc-list</string>
        <key>name</key>
        <string>meta.toc-list</string>
      </dict>
      <dict>
        <key>match</key>
        <string>constant.numeric</string>
        <key>name</key>
        <string>constant.numeric</string>
      </dict>
      <dict>
        <key>match</key>
        <string>constant.numeric.integer</string>
        <key>name</key>
        <string>constant.numeric.integer</string>
      </dict>
      <dict>
        <key>match</key>
        <string>constant.numeric.integer.binary</string>
        <key>name</key>
        <string>constant.numeric.integer.binary</string>
      </dict>
      <dict>
        <key>match</key>
        <string>constant.numeric.integer.octal</string>
        <key>name</key>
        <string>constant.numeric.integer.octal</string>
      </dict>
      <dict>
        <key>match</key>
        <string>constant.numeric.integer.decimal</string>
        <key>name</key>
        <string>constant.numeric.integer.decimal</string>
      </dict>
      <dict>
        <key>match</key>
        <string>constant.numeric.integer.hexadecimal</string>
        <key>name</key>
        <string>constant.numeric.integer.hexadecimal</string>
      </dict>
      <dict>
        <key>match</key>
        <string>constant.numeric.integer.other</string>
        <key>name</key>
        <string>constant.numeric.integer.other</string>
      </dict>
      <dict>
        <key>match</key>
        <string>constant.numeric.float</string>
        <key>name</key>
        <string>constant.numeric.float</string>
      </dict>
      <dict>
        <key>match</key>
        <string>constant.numeric.float.binary</string>
        <key>name</key>
        <string>constant.numeric.float.binary</string>
      </dict>
      <dict>
        <key>match</key>
        <string>constant.numeric.float.octal</string>
        <key>name</key>
        <string>constant.numeric.float.octal</string>
      </dict>
      <dict>
        <key>match</key>
        <string>constant.numeric.float.decimal</string>
        <key>name</key>
        <string>constant.numeric.float.decimal</string>
      </dict>
      <dict>
        <key>match</key>
        <string>constant.numeric.float.hexadecimal</string>
        <key>name</key>
        <string>constant.numeric.float.hexadecimal</string>
      </dict>
      <dict>
        <key>match</key>
        <string>constant.numeric.float.other</string>
        <key>name</key>
        <string>constant.numeric.float.other</string>
      </dict>
      <dict>
        <key>match</key>
        <string>constant.numeric.complex</string>
        <key>name</key>
        <string>constant.numeric.complex</string>
      </dict>
      <dict>
        <key>match</key>
        <string>constant.numeric.complex.real</string>
        <key>name</key>
        <string>constant.numeric.complex.real</string>
      </dict>
      <dict>
        <key>match</key>
        <string>constant.numeric.complex.imaginary</string>
        <key>name</key>
        <string>constant.numeric.complex.imaginary</string>
      </dict>
      <dict>
        <key>match</key>
        <string>constant.language</string>
        <key>name</key>
        <string>constant.language</string>
      </dict>
      <dict>
        <key>match</key>
        <string>constant.character.escape</string>
        <key>name</key>
        <string>constant.character.escape</string>
      </dict>
      <dict>
        <key>match</key>
        <string>constant.other.placeholder</string>
        <key>name</key>
        <string>constant.other.placeholder</string>
      </dict>
      <dict>
        <key>match</key>
        <string>constant.other</string>
        <key>name</key>
        <string>constant.other</string>
      </dict>
      <dict>
        <key>match</key>
        <string>entity.name.tag</string>
        <key>name</key>
        <string>entity.name.tag</string>
      </dict>
      <dict>
        <key>match</key>
        <string>entity.other.attribute-name</string>
        <key>name</key>
        <string>entity.other.attribute-name</string>
      </dict>
      <dict>
        <key>match</key>
        <string>entity.name.type.class</string>
        <key>name</key>
        <string>entity.name.type.class</string>
      </dict>
      <dict>
        <key>match</key>
        <string>entity.name.type.struct</string>
        <key>name</key>
        <string>entity.name.type.struct</string>
      </dict>
      <dict>
        <key>match</key>
        <string>entity.name.class</string>
        <key>name</key>
        <string>entity.name.class</string>
      </dict>
      <dict>
        <key>match</key>
        <string>entity.name.struct</string>
        <key>name</key>
        <string>entity.name.struct</string>
      </dict>
      <dict>
        <key>match</key>
        <string>entity.name.enum</string>
        <key>name</key>
        <string>entity.name.enum</string>
      </dict>
      <dict>
        <key>match</key>
        <string>entity.name.union</string>
        <key>name</key>
        <string>entity.name.union</string>
      </dict>
      <dict>
        <key>match</key>
        <string>entity.name.trait</string>
        <key>name</key>
        <string>entity.name.trait</string>
      </dict>
      <dict>
        <key>match</key>
        <string>entity.name.interface</string>
        <key>name</key>
        <string>entity.name.interface</string>
      </dict>
      <dict>
        <key>match</key>
        <string>entity.name.impl</string>
        <key>name</key>
        <string>entity.name.impl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>entity.name.type</string>
        <key>name</key>
        <string>entity.name.type</string>
      </dict>
      <dict>
        <key>match</key>
        <string>entity.name.class.forward-decl</string>
        <key>name</key>
        <string>entity.name.class.forward-decl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>entity.other.inherited-class</string>
        <key>name</key>
        <string>entity.other.inherited-class</string>
      </dict>
      <dict>
        <key>match</key>
        <string>entity.name.function</string>
        <key>name</key>
        <string>entity.name.function</string>
      </dict>
      <dict>
        <key>match</key>
        <string>entity.name.function.constructor</string>
        <key>name</key>
        <string>entity.name.function.constructor</string>
      </dict>
      <dict>
        <key>match</key>
        <string>entity.name.function.destructor</string>
        <key>name</key>
        <string>entity.name.function.destructor</string>
      </dict>
      <dict>
        <key>match</key>
        <string>entity.name.namespace</string>
        <key>name</key>
        <string>entity.name.namespace</string>
      </dict>
      <dict>
        <key>match</key>
        <string>variable.other.constant</string>
        <key>name</key>
        <string>variable.other.constant</string>
      </dict>
      <dict>
        <key>match</key>
        <string>entity.name.constant</string>
        <key>name</key>
        <string>entity.name.constant</string>
      </dict>
      <dict>
        <key>match</key>
        <string>entity.name.label</string>
        <key>name</key>
        <string>entity.name.label</string>
      </dict>
      <dict>
        <key>match</key>
        <string>entity.name.section</string>
        <key>name</key>
        <string>entity.name.section</string>
      </dict>
      <dict>
        <key>match</key>
        <string>entity.name</string>
        <key>name</key>
        <string>entity.name</string>
      </dict>
      <dict>
        <key>match</key>
        <string>invalid.illegal</string>
        <key>name</key>
        <string>invalid.illegal</string>
      </dict>
      <dict>
        <key>match</key>
        <string>invalid.deprecated</string>
        <key>name</key>
        <string>invalid.deprecated</string>
      </dict>
      <dict>
        <key>match</key>
        <string>keyword.control</string>
        <key>name</key>
        <string>keyword.control</string>
      </dict>
      <dict>
        <key>match</key>
        <string>keyword.control.conditional</string>
        <key>name</key>
        <string>keyword.control.conditional</string>
      </dict>
      <dict>
        <key>match</key>
        <string>keyword.control.import</string>
        <key>name</key>
        <string>keyword.control.import</string>
      </dict>
      <dict>
        <key>match</key>
        <string>punctuation.definition.keyword</string>
        <key>name</key>
        <string>punctuation.definition.keyword</string>
      </dict>
      <dict>
        <key>match</key>
        <string>keyword.operator</string>
        <key>name</key>
        <string>keyword.operator</string>
      </dict>
      <dict>
        <key>match</key>
        <string>keyword.operator.assignment</string>
        <key>name</key>
        <string>keyword.operator.assignment</string>
      </dict>
      <dict>
        <key>match</key>
        <string>keyword.operator.arithmetic</string>
        <key>name</key>
        <string>keyword.operator.arithmetic</string>
      </dict>
      <dict>
        <key>match</key>
        <string>keyword.operator.bitwise</string>
        <key>name</key>
        <string>keyword.operator.bitwise</string>
      </dict>
      <dict>
        <key>match</key>
        <string>keyword.operator.logical</string>
        <key>name</key>
        <string>keyword.operator.logical</string>
      </dict>
      <dict>
        <key>match</key>
        <string>keyword.operator.word</string>
        <key>name</key>
        <string>keyword.operator.word</string>
      </dict>
      <dict>
        <key>match</key>
        <string>keyword.other.type</string>
        <key>name</key>
        <string>keyword.other.type</string>
      </dict>
      <dict>
        <key>match</key>
        <string>support.constant.ext</string>
        <key>name</key>
        <string>support.constant.ext</string>
      </dict>
      <dict>
        <key>match</key>
        <string>keyword.other</string>
        <key>name</key>
        <string>keyword.other</string>
      </dict>
      <dict>
        <key>match</key>
        <string>markup.heading</string>
        <key>name</key>
        <string>markup.heading</string>
      </dict>
      <dict>
        <key>match</key>
        <string>markup.list.unnumbered</string>
        <key>name</key>
        <string>markup.list.unnumbered</string>
      </dict>
      <dict>
        <key>match</key>
        <string>markup.list.numbered</string>
        <key>name</key>
        <string>markup.list.numbered</string>
      </dict>
      <dict>
        <key>match</key>
        <string>markup.bold</string>
        <key>name</key>
        <string>markup.bold</string>
      </dict>
      <dict>
        <key>match</key>
        <string>markup.italic</string>
        <key>name</key>
        <string>markup.italic</string>
      </dict>
      <dict>
        <key>match</key>
        <string>markup.underline</string>
        <key>name</key>
        <string>markup.underline</string>
      </dict>
      <dict>
        <key>match</key>
        <string>markup.inserted</string>
        <key>name</key>
        <string>markup.inserted</string>
      </dict>
      <dict>
        <key>match</key>
        <string>markup.deleted</string>
        <key>name</key>
        <string>markup.deleted</string>
      </dict>
      <dict>
        <key>match</key>
        <string>markup.underline.link</string>
        <key>name</key>
        <string>markup.underline.link</string>
      </dict>
      <dict>
        <key>match</key>
        <string>markup.quote</string>
        <key>name</key>
        <string>markup.quote</string>
      </dict>
      <dict>
        <key>match</key>
        <string>markup.raw.inline</string>
        <key>name</key>
        <string>markup.raw.inline</string>
      </dict>
      <dict>
        <key>match</key>
        <string>markup.raw.block</string>
        <key>name</key>
        <string>markup.raw.block</string>
      </dict>
      <dict>
        <key>match</key>
        <string>markup.other</string>
        <key>name</key>
        <string>markup.other</string>
      </dict>
      <dict>
        <key>match</key>
        <string>meta.class</string>
        <key>name</key>
        <string>meta.class</string>
      </dict>
      <dict>
        <key>match</key>
        <string>meta.struct</string>
        <key>name</key>
        <string>meta.struct</string>
      </dict>
      <dict>
        <key>match</key>
        <string>meta.enum</string>
        <key>name</key>
        <string>meta.enum</string>
      </dict>
      <dict>
        <key>match</key>
        <string>meta.union</string>
        <key>name</key>
        <string>meta.union</string>
      </dict>
      <dict>
        <key>match</key>
        <string>meta.trait</string>
        <key>name</key>
        <string>meta.trait</string>
      </dict>
      <dict>
        <key>match</key>
        <string>meta.interface</string>
        <key>name</key>
        <string>meta.interface</string>
      </dict>
      <dict>
        <key>match</key>
        <string>meta.impl</string>
        <key>name</key>
        <string>meta.impl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>meta.type</string>
        <key>name</key>
        <string>meta.type</string>
      </dict>
      <dict>
        <key>match</key>
        <string>meta.function</string>
        <key>name</key>
        <string>meta.function</string>
      </dict>
      <dict>
        <key>match</key>
        <string>meta.function.parameters</string>
        <key>name</key>
        <string>meta.function.parameters</string>
      </dict>
      <dict>
        <key>match</key>
        <string>meta.function.return-type</string>
        <key>name</key>
        <string>meta.function.return-type</string>
      </dict>
      <dict>
        <key>match</key>
        <string>meta.namespace</string>
        <key>name</key>
        <string>meta.namespace</string>
      </dict>
      <dict>
        <key>match</key>
        <string>meta.preprocessor</string>
        <key>name</key>
        <string>meta.preprocessor</string>
      </dict>
      <dict>
        <key>match</key>
        <string>meta.annotation</string>
        <key>name</key>
        <string>meta.annotation</string>
      </dict>
      <dict>
        <key>match</key>
        <string>variable.annotation</string>
        <key>name</key>
        <string>variable.annotation</string>
      </dict>
      <dict>
        <key>match</key>
        <string>meta.annotation</string>
        <key>name</key>
        <string>meta.annotation</string>
      </dict>
      <dict>
        <key>match</key>
        <string>meta.annotation.identifier</string>
        <key>name</key>
        <string>meta.annotation.identifier</string>
      </dict>
      <dict>
        <key>match</key>
        <string>meta.annotation.parameters</string>
        <key>name</key>
        <string>meta.annotation.parameters</string>
      </dict>
      <dict>
        <key>match</key>
        <string>punctuation.definition.annotation</string>
        <key>name</key>
        <string>punctuation.definition.annotation</string>
      </dict>
      <dict>
        <key>match</key>
        <string>meta.path</string>
        <key>name</key>
        <string>meta.path</string>
      </dict>
      <dict>
        <key>match</key>
        <string>variable.function</string>
        <key>name</key>
        <string>variable.function</string>
      </dict>
      <dict>
        <key>match</key>
        <string>support.function</string>
        <key>name</key>
        <string>support.function</string>
      </dict>
      <dict>
        <key>match</key>
        <string>meta.function-call</string>
        <key>name</key>
        <string>meta.function-call</string>
      </dict>
      <dict>
        <key>match</key>
        <string>meta.block</string>
        <key>name</key>
        <string>meta.block</string>
      </dict>
      <dict>
        <key>match</key>
        <string>punctuation.section.block.begin</string>
        <key>name</key>
        <string>punctuation.section.block.begin</string>
      </dict>
      <dict>
        <key>match</key>
        <string>punctuation.section.block.end</string>
        <key>name</key>
        <string>punctuation.section.block.end</string>
      </dict>
      <dict>
        <key>match</key>
        <string>meta.braces</string>
        <key>name</key>
        <string>meta.braces</string>
      </dict>
      <dict>
        <key>match</key>
        <string>punctuation.section.braces.begin</string>
        <key>name</key>
        <string>punctuation.section.braces.begin</string>
      </dict>
      <dict>
        <key>match</key>
        <string>punctuation.section.braces.end</string>
        <key>name</key>
        <string>punctuation.section.braces.end</string>
      </dict>
      <dict>
        <key>match</key>
        <string>meta.group</string>
        <key>name</key>
        <string>meta.group</string>
      </dict>
      <dict>
        <key>match</key>
        <string>punctuation.section.group.begin</string>
        <key>name</key>
        <string>punctuation.section.group.begin</string>
      </dict>
      <dict>
        <key>match</key>
        <string>punctuation.section.group.end</string>
        <key>name</key>
        <string>punctuation.section.group.end</string>
      </dict>
      <dict>
        <key>match</key>
        <string>meta.parens</string>
        <key>name</key>
        <string>meta.parens</string>
      </dict>
      <dict>
        <key>match</key>
        <string>punctuation.section.parens.begin</string>
        <key>name</key>
        <string>punctuation.section.parens.begin</string>
      </dict>
      <dict>
        <key>match</key>
        <string>punctuation.section.parens.end</string>
        <key>name</key>
        <string>punctuation.section.parens.end</string>
      </dict>
      <dict>
        <key>match</key>
        <string>meta.brackets</string>
        <key>name</key>
        <string>meta.brackets</string>
      </dict>
      <dict>
        <key>match</key>
        <string>punctuation.section.brackets.begin</string>
        <key>name</key>
        <string>punctuation.section.brackets.begin</string>
      </dict>
      <dict>
        <key>match</key>
        <string>punctuation.section.brackets.end</string>
        <key>name</key>
        <string>punctuation.section.brackets.end</string>
      </dict>
      <dict>
        <key>match</key>
        <string>meta.generic</string>
        <key>name</key>
        <string>meta.generic</string>
      </dict>
      <dict>
        <key>match</key>
        <string>punctuation.definition.generic.begin</string>
        <key>name</key>
        <string>punctuation.definition.generic.begin</string>
      </dict>
      <dict>
        <key>match</key>
        <string>punctuation.definition.generic.end</string>
        <key>name</key>
        <string>punctuation.definition.generic.end</string>
      </dict>
      <dict>
        <key>match</key>
        <string>meta.tag</string>
        <key>name</key>
        <string>meta.tag</string>
      </dict>
      <dict>
        <key>match</key>
        <string>meta.paragraph</string>
        <key>name</key>
        <string>meta.paragraph</string>
      </dict>
      <dict>
        <key>match</key>
        <string>punctuation.separator</string>
        <key>name</key>
        <string>punctuation.separator</string>
      </dict>
      <dict>
        <key>match</key>
        <string>punctuation.terminator</string>
        <key>name</key>
        <string>punctuation.terminator</string>
      </dict>
      <dict>
        <key>match</key>
        <string>punctuation.separator.continuation</string>
        <key>name</key>
        <string>punctuation.separator.continuation</string>
      </dict>
      <dict>
        <key>match</key>
        <string>punctuation.accessor</string>
        <key>name</key>
        <string>punctuation.accessor</string>
      </dict>
      <dict>
        <key>match</key>
        <string>storage.type</string>
        <key>name</key>
        <string>storage.type</string>
      </dict>
      <dict>
        <key>match</key>
        <string>storage.modifier</string>
        <key>name</key>
        <string>storage.modifier</string>
      </dict>
      <dict>
        <key>match</key>
        <string>storage.type.function keyword.declaration.function</string>
        <key>name</key>
        <string>storage.type.function keyword.declaration.function</string>
      </dict>
      <dict>
        <key>match</key>
        <string>storage.type.class keyword.declaration.class</string>
        <key>name</key>
        <string>storage.type.class keyword.declaration.class</string>
      </dict>
      <dict>
        <key>match</key>
        <string>storage.type.struct keyword.declaration.struct</string>
        <key>name</key>
        <string>storage.type.struct keyword.declaration.struct</string>
      </dict>
      <dict>
        <key>match</key>
        <string>storage.type.enum keyword.declaration.enum</string>
        <key>name</key>
        <string>storage.type.enum keyword.declaration.enum</string>
      </dict>
      <dict>
        <key>match</key>
        <string>storage.type.union keyword.declaration.union</string>
        <key>name</key>
        <string>storage.type.union keyword.declaration.union</string>
      </dict>
      <dict>
        <key>match</key>
        <string>storage.type.trait keyword.declaration.trait</string>
        <key>name</key>
        <string>storage.type.trait keyword.declaration.trait</string>
      </dict>
      <dict>
        <key>match</key>
        <string>storage.type.interface keyword.declaration.interface</string>
        <key>name</key>
        <string>storage.type.interface keyword.declaration.interface</string>
      </dict>
      <dict>
        <key>match</key>
        <string>storage.type.impl keyword.declaration.impl</string>
        <key>name</key>
        <string>storage.type.impl keyword.declaration.impl</string>
      </dict>
      <dict>
        <key>match</key>
        <string>storage.type keyword.declaration.type</string>
        <key>name</key>
        <string>storage.type keyword.declaration.type</string>
      </dict>
      <dict>
        <key>match</key>
        <string>string.quoted.single</string>
        <key>name</key>
        <string>string.quoted.single</string>
      </dict>
      <dict>
        <key>match</key>
        <string>string.quoted.double</string>
        <key>name</key>
        <string>string.quoted.double</string>
      </dict>
      <dict>
        <key>match</key>
        <string>string.quoted.triple</string>
        <key>name</key>
        <string>string.quoted.triple</string>
      </dict>
      <dict>
        <key>match</key>
        <string>string.quoted.other</string>
        <key>name</key>
        <string>string.quoted.other</string>
      </dict>
      <dict>
        <key>match</key>
        <string>meta.string</string>
        <key>name</key>
        <string>meta.string</string>
      </dict>
      <dict>
        <key>match</key>
        <string>punctuation.definition.string.begin</string>
        <key>name</key>
        <string>punctuation.definition.string.begin</string>
      </dict>
      <dict>
        <key>match</key>
        <string>punctuation.definition.string.end</string>
        <key>name</key>
        <string>punctuation.definition.string.end</string>
      </dict>
      <dict>
        <key>match</key>
        <string>string.unquoted</string>
        <key>name</key>
        <string>string.unquoted</string>
      </dict>
      <dict>
        <key>match</key>
        <string>string.regexp</string>
        <key>name</key>
        <string>string.regexp</string>
      </dict>
      <dict>
        <key>match</key>
        <string>string</string>
        <key>name</key>
        <string>string</string>
      </dict>
      <dict>
        <key>match</key>
        <string>meta.interpolation</string>
        <key>name</key>
        <string>meta.interpolation</string>
      </dict>
      <dict>
        <key>match</key>
        <string>punctuation.section.interpolation.begin</string>
        <key>name</key>
        <string>punctuation.section.interpolation.begin</string>
      </dict>
      <dict>
        <key>match</key>
        <string>punctuation.section.interpolation.end</string>
        <key>name</key>
        <string>punctuation.section.interpolation.end</string>
      </dict>
      <dict>
        <key>match</key>
        <string>source.language-suffix.embedded</string>
        <key>name</key>
        <string>source.language-suffix.embedded</string>
      </dict>
      <dict>
        <key>match</key>
        <string>support.constant</string>
        <key>name</key>
        <string>support.constant</string>
      </dict>
      <dict>
        <key>match</key>
        <string>support.module</string>
        <key>name</key>
        <string>support.module</string>
      </dict>
      <dict>
        <key>match</key>
        <string>support.type</string>
        <key>name</key>
        <string>support.type</string>
      </dict>
      <dict>
        <key>match</key>
        <string>support.class</string>
        <key>name</key>
        <string>support.class</string>
      </dict>
      <dict>
        <key>match</key>
        <string>text.html.basic</string>
        <key>name</key>
        <string>text.html.basic</string>
      </dict>
      <dict>
        <key>match</key>
        <string>text.html.markdown</string>
        <key>name</key>
        <string>text.html.markdown</string>
      </dict>
      <dict>
        <key>match</key>
        <string>text.html</string>
        <key>name</key>
        <string>text.html</string>
      </dict>
      <dict>
        <key>match</key>
        <string>text.xml</string>
        <key>name</key>
        <string>text.xml</string>
      </dict>
      <dict>
        <key>match</key>
        <string>variable.other</string>
        <key>name</key>
        <string>variable.other</string>
      </dict>
      <dict>
        <key>match</key>
        <string>variable.other.readwrite</string>
        <key>name</key>
        <string>variable.other.readwrite</string>
      </dict>
      <dict>
        <key>match</key>
        <string>punctuation.definition.variable</string>
        <key>name</key>
        <string>punctuation.definition.variable</string>
      </dict>
      <dict>
        <key>match</key>
        <string>variable.language</string>
        <key>name</key>
        <string>variable.language</string>
      </dict>
      <dict>
        <key>match</key>
        <string>variable.parameter</string>
        <key>name</key>
        <string>variable.parameter</string>
      </dict>
      <dict>
        <key>match</key>
        <string>variable.other.member</string>
        <key>name</key>
        <string>variable.other.member</string>
      </dict>
      <dict>
        <key>match</key>
        <string>keyword.declaration</string>
        <key>name</key>
        <string>keyword.declaration</string>
      </dict>
    </array>
  </dict>
</plist>
