name: Lint

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - '**'

env:
  CI: true

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v1
    - run: yarn install
    - name: Lint all configs
      run: yarn run ci:lint
